### ISSUE TITLE
Duplicated geometries after creation

### ISSUE THREAD

**Issue by unibasil** [blazek/spline#4]
QGIS 2.6.1 with Spline plugin 0.1.5:
If I am drawing spline, pressing right mouse button, filling attributes and pressing **Ok**,  I've got new perfect geometry. But not just one: selecting Move Feature(s) tool and shifting this geometry reveals the second identical cloned geometry.

Tested in Ubuntu 14.04, WIndows 7 (32 and 64 versions).

**Comment by blazek** [comment]
Confirmed, I'll try to fix soon.

**Comment by blazek** [comment]
Fixed in 65f162f and release 0.1.6.

The problem was caused by changes in QGIS 2.4 attributes dialog, I believe.
